region: us-west-2

function_name: lqn-datacredito-dev
handler: service.handler
description: Consume the api de datacredito
runtime: python3.8
role: avatarLambda

bucket_name: "lqn-datacredito"
s3_key_prefix: "dev/"

aws_access_key_id: AKIAJRAKXZZIJ4HWDEMA
aws_secret_access_key: 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

build:
  source_directories: lib
